rootProject.name = "sample"
include(":app")
include(":domain")
include(":data:data-core")
include(":data:data-remote")
include(":features:cities")
include(":data:data-local")
include(":core:core-kotlin")
include(":utility:bases")
include(":utility:bases-android")
include(":test:core-test")
include(":navigation")
